apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-mysql-pvc
  namespace: demo-wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-wordpress-pvc
  namespace: demo-wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi